### ISSUE TITLE
Cheating detected

### ISSUE THREAD

**Issue by ScurySnek2** [ecc521/gimkit-bot#13] opened 2020-05-04 16:26 UTC
![image](https://user-images.githubusercontent.com/64798216/80989104-50c1dc80-8de9-11ea-91ba-632d29fdb485.png)

When ran on firefox, it does not answer any questions, and after about 30 seconds it quits and gives a screen that says cheating is detected

**Comment by ecc521** [comment] 2020-05-06 13:55
Duplicate of https://github.com/ecc521/gimkit-bot/issues/8

**Closed by ecc521** 2020-05-06 13:55 UTC
Labels: duplicate

**Comment by ecc521** [comment] 2020-05-06 13:57
GimKit kicked you because it detected you answering questions extremely quickly, not because of the bot. This rate limiting often leads to human players getting kicked too, and is currently not handled by the bot.
